// Generated by CoffeeScript 1.4.0
(function() {
  var transformer;

  transformer = require("./transformer");

  module.exports = {
    cast: function(typeClass) {
      return transformer().cast(typeClass);
    },
    map: function(typeClass) {
      return transformer().map(typeClass);
    }
  };

}).call(this);
