// Generated by CoffeeScript 1.6.2
(function() {
  var transformer;

  transformer = require("./transformer");

  module.exports = transformer;

  module.exports.cast = function(typeClass) {
    return transformer().cast(typeClass);
  };

  module.exports.map = function(typeClass) {
    return transformer().map(typeClass);
  };

}).call(this);
