// Generated by CoffeeScript 1.6.2
(function() {
  var async, getArrayTypeCaster, getClassTypeCaster, getSimpleDataTypeCaster, getTypeCaster, isa;

  isa = require("isa");

  async = require("async");

  /*
  */


  getArrayTypeCaster = function() {
    return function(value) {
      if (isa.array(value)) {
        return value;
      }
      return [value];
    };
  };

  /*
  */


  getSimpleDataTypeCaster = function(typeClass) {
    return function(value) {
      return typeClass(value);
    };
  };

  /*
  */


  getClassTypeCaster = function(typeClass) {
    return function(value) {
      if (value && value.constructor === typeClass) {
        return value;
      }
      return new typeClass(value);
    };
  };

  /*
  */


  getTypeCaster = function(typeClass) {
    if (typeClass === Array) {
      return getArrayTypeCaster();
    }
    if ((typeClass === String) || (typeClass === Number)) {
      return getSimpleDataTypeCaster(typeClass);
    }
    return getClassTypeCaster(typeClass);
  };

  /*
  */


  module.exports = function(options) {
    var self, _transform;

    if (options == null) {
      options = {};
    }
    _transform = [];
    /*
    */

    self = function(value, next) {
      if (arguments.length > 1 && isa["function"](arguments[arguments.length - 1])) {
        return self.async(value, next);
      } else {
        return self.sync.apply(null, arguments);
      }
    };
    /*
    */

    self.async = function(value, next) {
      return async.eachSeries(_transform, (function(transformer, next) {
        if (transformer.async) {
          return transformer.transform(value, function(err, result) {
            if (err) {
              return next(err);
            }
            return next(null, value = result);
          });
        } else {
          value = transformer.transform(value);
          return next();
        }
      }), function(err, result) {
        if (err) {
          return next(err);
        }
        return next(null, value);
      });
    };
    /*
    */

    self.sync = function() {
      var transformer, _i, _len;

      for (_i = 0, _len = _transform.length; _i < _len; _i++) {
        transformer = _transform[_i];
        arguments[0] = transformer.transform.apply(null, arguments);
      }
      return arguments[0];
    };
    /*
    */

    self.cast = function(typeClass) {
      _transform.push({
        transform: getTypeCaster(typeClass)
      });
      return this;
    };
    /*
    */

    self.map = function(fn) {
      _transform.push({
        async: fn.length > 1,
        transform: fn
      });
      return this;
    };
    return self;
  };

}).call(this);
